main:
  - name: "About"
    url: "#about"
    weight: 1

  - name: "Members"
    url: "/members/"
    weight: 2

  - name: "Projects"
    url: "/projects/"
    weight: 3

  - name: "GitHub"
    url: "https://github.com/knc-neural-calculus"
    weight: 4
  
  - name: "Join"
    url: "mailto:admin@knc.ai"
    weight: 5