# base directories
# ==============================
# NOTE: these are all relative to the location of the config file!
# where the script will look for markdown files
content: &CONTENT_DIR "./content/"
# where HTML files will be generated
public: &PUBLIC_DIR "./docs/"
# referenced only in this yaml file, for now
resources: &RESOURCES_DIR !join [*CONTENT_DIR, "resources/"]

# other things
# ==============================
make_index_files: true # whether to treat files with `index: true` specially
generated_index_suffix: "._index.md" # dont worry about this, its for generating temporary files

# whether to give each HTML file a final pass with the mustache renderer, 
# with the frontmatter from the markdown source passed as the context
mustache_rerender: true 

# pandoc stuff
# ==============================
# these items will be passed as arguments to pandoc
# note: items which are lists (e.g. `foo: [a, b, c]`) will be passed as `--foo a --foo b --foo c`
# note: `!join` is a custom directive that will add the elements of the list together. useful for concatenating strings
__pandoc__:
  include-in-header: !join [*RESOURCES_DIR, "header.html"] # passed as '--include-in-header'
  include-before-body: !join [*RESOURCES_DIR, "before-body.html"] # passed as '--include-before-body'
  include-after-body: !join [*RESOURCES_DIR, "after-body.html"] # passed as '--include-after-body'

  # these should be paths to any pandoc filters you'd like to use. 
  # if you dont have any, just have it be an empty list
  filter: 
    - "pandoc-sitegen/filters/links_md2html.py"

  email-obfuscation: 'references'